"""empty message

Revision ID: 555f33c4f011
Revises: dc42dae9de87
Create Date: 2023-09-14 11:19:33.798932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555f33c4f011'
down_revision = 'dc42dae9de87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catgory_desc', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('catgory_desc')

    # ### end Alembic commands ###
